### ISSUE TITLE
rules_elm is not worked with Bazel 5.0.0

### ISSUE THREAD

**Issue by matsubara0507** [matsubara0507/rules_elm#8]
```
$ bazelisk build //examples/build-project:index
Starting local Bazel server and connecting to it...
INFO: Analyzed target //examples/build-project:index (47 packages loaded, 324 targets configured).
INFO: Found 1 target...
ERROR: /.../rules_elm/examples/build-project/BUILD.bazel:3:17: Action examples/build-project/.elm.zip failed: (Exit 1): elm_dependencies failed: error executing command bazel-out/host/bin/elm/private/elm_dependencies examples/build-project

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/.../sandbox/darwin-sandbox/2/execroot/rules_elm/bazel-out/host/bin/elm/private/elm_dependencies.runfiles/rules_elm/elm/private/elm_dependencies.py", line 45, in <module>
    run([elm_runtime_path, "make", "Main.elm"])
  File "/.../sandbox/darwin-sandbox/2/execroot/rules_elm/bazel-out/host/bin/elm/private/elm_dependencies.runfiles/rules_elm/elm/private/elm_dependencies.py", line 21, in run
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, *args, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/.../sandbox/darwin-sandbox/2/execroot/rules_elm/bazel-out/host/bin/external/rules_elm_compiler_mac/elm'
Target //examples/build-project:index failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 19.849s, Critical Path: 1.13s
INFO: 12 processes: 11 internal, 1 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by matsubara0507** [comment]
Different `cfg = None` behavior between 4.2.2 and 5.0.0.

- 4.2.2 : `cfg = None` is `"host"`
- 5.0.0 : `cfg = None` is `"target"`

https://docs.bazel.build/versions/5.0.0/skylark/rules.html#configurations
> Tools that are executed as part of the build (e.g., compilers, code generators) should be built for an exec configuration. In this case, specify cfg="exec" in the attribute.

> Note: Historically, Bazel didn’t have the concept of execution platforms, and instead all build actions were considered to run on the host machine. Because of this, there is a single “host” configuration, and a “host” transition that can be used to build a dependency in the host configuration. Many rules still use the “host” transition for their tools, but this is currently deprecated and being migrated to use “exec” transitions where possible.

But, should use `cfg = "exec"`.
